import html
import json
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LANG_ORDER = ["ko", "en", "zh"]
DEFAULT_LANG = "en"
STORAGE_KEY = "sunghunkim-landing:lang"
PRETENDARD = "https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"
FAVICON = (
    "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E"
    "%3Crect width='64' height='64' rx='12' fill='%230B1420'/%3E%3Ctext x='50%25' y='54%25' "
    "text-anchor='middle' dominant-baseline='middle' font-family='Arial,Helvetica,sans-serif' "
    "font-size='28' font-weight='700' fill='%234C8DFF'%3ESK%3C/text%3E%3C/svg%3E"
)
NOTICE = "<!-- Generated by build.py from content/*.toml. Edit the content files, then run: python build.py -->"

GLOBE = (
    '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">'
    '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 2.7 3.8 5.7 3.8 9s-1.3 6.3-3.8 9'
    'c-2.5-2.7-3.8-5.7-3.8-9S9.5 5.7 12 3z"/></svg>'
)
CHEVRON = (
    '<svg class="chev" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" '
    'stroke-width="2"><path d="m6 9 6 6 6-6"/></svg>'
)


def fmt(text):
    """Escape text, then apply the content markup: *em*, _{sub}, {ko:...} language spans, newlines."""
    out = html.escape(text, quote=False)
    out = re.sub(r"\{(ko|en|zh-Hans):(.+?)\}", r'<span lang="\1">\2</span>', out)
    out = re.sub(r"\*(.+?)\*", r"<em>\1</em>", out)
    out = re.sub(r"_\{(.+?)\}", r"<sub>\1</sub>", out)
    return out.replace("\n", "<br>")


def attr(text):
    return html.escape(re.sub(r"\{(?:ko|en|zh-Hans):(.+?)\}", r"\1", text), quote=True)


def load():
    shared = tomllib.loads((ROOT / "content" / "shared.toml").read_text(encoding="utf-8"))
    langs = [
        tomllib.loads((ROOT / "content" / f"{code}.toml").read_text(encoding="utf-8"))
        for code in LANG_ORDER
    ]
    return shared, langs


def head_common(title, description, canonical, og_title, og_description, og_locale, locale_alts, langs, s, prefix):
    alternates = "\n".join(
        f'<link rel="alternate" hreflang="{l["hreflang"]}" href="{s["site_url"]}{l["code"]}/">' for l in langs
    )
    locale_meta = "\n".join(f'<meta property="og:locale:alternate" content="{loc}">' for loc in locale_alts)
    return f"""<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{attr(title)}</title>
<meta name="description" content="{attr(description)}">
<meta name="theme-color" content="#0B1420">
<link rel="canonical" href="{canonical}">
{alternates}
<link rel="alternate" hreflang="x-default" href="{s["site_url"]}">
<meta property="og:type" content="profile">
<meta property="og:locale" content="{og_locale}">
{locale_meta}
<meta property="og:title" content="{attr(og_title)}">
<meta property="og:description" content="{attr(og_description)}">
<meta property="og:image" content="{s["site_url"]}assets/portrait.jpg">
<meta property="og:url" content="{canonical}">
<meta name="twitter:card" content="summary">
<link rel="icon" href="{FAVICON}">
<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
<link rel="stylesheet" href="{PRETENDARD}">
<link rel="stylesheet" href="{prefix}assets/site.css">"""


def lang_menu(c, langs):
    items = []
    for l in langs:
        current = ' aria-current="page"' if l["code"] == c["code"] else ""
        items.append(
            f'          <li><a href="../{l["code"]}/" data-base="../{l["code"]}/" data-lang="{l["code"]}" '
            f'lang="{l["hreflang"]}" hreflang="{l["hreflang"]}"{current}>'
            f'{fmt(l["native"])}<small>{l["label"]}</small></a></li>'
        )
    items_html = "\n".join(items)
    return f"""<details class="lang">
        <summary aria-label="{attr(c["ui"]["lang_aria"])}">{GLOBE}<span>{c["label"]}</span>{CHEVRON}</summary>
        <ul class="lang-menu">
{items_html}
        </ul>
      </details>"""


def section_label(sec):
    intro = f'\n        <p>{fmt(sec["intro"])}</p>' if sec.get("intro") else ""
    return f"""<div class="section-label">
        <span class="eyebrow">{fmt(sec["eyebrow"])}</span>
        <h2>{fmt(sec["title"])}</h2>{intro}
      </div>"""


def render_stats(c):
    items = []
    for st in c["stats"]:
        unit = f'<small>{fmt(st["unit"])}</small>' if st.get("unit") else ""
        items.append(f"""        <li>
          <div class="stat-value num">{fmt(st["value"])}{unit}</div>
          <div class="stat-label">{fmt(st["label"])}</div>
          <div class="stat-note">{fmt(st["note"])}</div>
        </li>""")
    return "\n".join(items)


def render_expertise(c):
    items = []
    for it in c["expertise"]["items"]:
        items.append(f"""        <li>
          <h3>{fmt(it["title"])}</h3>
          <p>{fmt(it["body"])}</p>
          <div class="keys">{fmt(it["keys"])}</div>
        </li>""")
    return "\n".join(items)


def render_career(c):
    orgs = []
    for org in c["career"]["orgs"]:
        roles = []
        for r in org["roles"]:
            cls = "role is-current" if r.get("current") else "role"
            unit = f'\n              <div class="role-unit">{fmt(r["unit"])}</div>' if r.get("unit") else ""
            bullets = "\n".join(f"                <li>{fmt(b)}</li>" for b in r["bullets"])
            roles.append(f"""            <div class="{cls}">
              <div class="role-head"><h4>{fmt(r["title"])}</h4><span class="role-date num">{fmt(r["date"])}</span></div>{unit}
              <ul>
{bullets}
              </ul>
            </div>""")
        roles_html = "\n".join(roles)
        orgs.append(f"""        <article class="org">
          <div class="org-head">
            <div>
              <h3>{fmt(org["name"])}</h3>
              <div class="org-meta">{fmt(org["meta"])}</div>
            </div>
            <div class="org-span num">{fmt(org["span"])}</div>
          </div>
          <div class="roles">
{roles_html}
          </div>
        </article>""")
    return "\n\n".join(orgs)


def render_education(c):
    items = []
    for it in c["education"]["items"]:
        notes = "<br>".join(fmt(n) for n in it["notes"])
        items.append(f"""        <li>
          <div class="edu-year num">{fmt(it["year"])}</div>
          <h3>{fmt(it["degree"])}</h3>
          <div class="edu-inst">{fmt(it["inst"])}</div>
          <div class="edu-thesis">{notes}</div>
        </li>""")
    return "\n".join(items)


def record(year, title, sub, rid, rid_num):
    num = " num" if rid_num else ""
    return f"""            <li>
              <span class="rec-year num">{fmt(year)}</span>
              <div><div class="rec-title">{fmt(title)}</div><div class="rec-sub">{fmt(sub)}</div></div>
              <span class="rec-id{num}">{fmt(rid)}</span>
            </li>"""


def render_research(c, s):
    r = c["research"]
    patents = "\n".join(record(p["year"], p["title"], p["authors"], p["id"], True) for p in s["patents"])
    pubs = "\n".join(
        record(p["year"], p["title"], p["venue"], r["kinds"][p["kind"]], False) for p in s["publications"]
    )
    honors = "\n".join(
        f'              <li><span>{fmt(h["name"])}</span><span class="num">{fmt(h["year"])}</span></li>'
        for h in r["honors"]
    )
    members = "\n".join(f"              <li><span>{fmt(m)}</span></li>" for m in r["members"])
    return f"""<div class="block">
          <div class="block-head"><h3>{fmt(r["patents_title"])}</h3><span>{fmt(r["patents_meta"])}</span></div>
          <ol class="records">
{patents}
          </ol>
        </div>

        <div class="block">
          <div class="block-head"><h3>{fmt(r["pubs_title"])}</h3><span>{fmt(r["pubs_meta"])}</span></div>
          <ol class="records">
{pubs}
          </ol>
        </div>

        <div class="block honors">
          <div>
            <div class="block-head"><h3>{fmt(r["honors_title"])}</h3></div>
            <ul class="plain-list">
{honors}
            </ul>
          </div>
          <div>
            <div class="block-head"><h3>{fmt(r["members_title"])}</h3></div>
            <ul class="plain-list">
{members}
            </ul>
          </div>
        </div>"""


def page(c, s, langs):
    ui, hero, profile, ct = c["ui"], c["hero"], c["profile"], c["contact"]
    canonical = f'{s["site_url"]}{c["code"]}/'
    head = head_common(
        c["title"], c["description"], canonical, c["og_title"], c["og_description"], c["og_locale"],
        [l["og_locale"] for l in langs if l["code"] != c["code"]], langs, s, "../",
    )
    fonts = "\n".join(f'<link rel="stylesheet" href="{attr(href)}">' for href in c.get("font_links", []))
    nav_links = "\n".join(f'      <a href="#{n["id"]}">{fmt(n["label"])}</a>' for n in ui["nav"])
    affil = "\n".join(f"            <li>{fmt(a)}</li>" for a in hero["affil"])
    topics = "\n".join(f"              <li>{fmt(t)}</li>" for t in ct["topics"])

    return f"""<!doctype html>
{NOTICE}
<html lang="{c["html_lang"]}">
<head>
{head}
{fonts}
</head>
<body>

<header class="nav">
  <div class="wrap">
    <a class="brand" href="#top"><strong>{fmt(ui["brand"])}</strong><span>{fmt(ui["brand_sub"])}</span></a>
    <nav class="nav-links" aria-label="{attr(ui["nav_aria"])}">
{nav_links}
    </nav>
    <div class="nav-actions">
      {lang_menu(c, langs)}
      <a class="btn btn-primary" href="#contact">{fmt(ui["contact_cta"])}</a>
    </div>
  </div>
</header>

<main>

  <section class="hero" id="top">
    <div class="wrap">
      <div>
        <span class="eyebrow">{fmt(hero["eyebrow"])}</span>
        <h1>{fmt(hero["name"])}<span class="alt">{fmt(hero["alt"])}</span></h1>
        <p class="lead">{fmt(hero["lead"])}</p>
        <p class="sub">{fmt(hero["sub"])}</p>
        <div class="hero-actions">
          <a class="btn btn-primary" href="#contact">{fmt(hero["cta_primary"])}</a>
          <a class="btn btn-secondary" href="#career">{fmt(hero["cta_secondary"])}</a>
        </div>
        <div class="affil">
          <div class="affil-label">{fmt(hero["affil_label"])}</div>
          <ul>
{affil}
          </ul>
        </div>
      </div>
      <figure>
        <div class="portrait">
          <img src="../assets/portrait.jpg" width="400" height="500" alt="{attr(hero["photo_alt"])}">
        </div>
        <figcaption><strong>{fmt(hero["caption_title"])}</strong>{fmt(hero["caption_sub"])}</figcaption>
      </figure>
    </div>
  </section>

  <section class="stats" aria-label="{attr(ui["stats_aria"])}">
    <div class="wrap">
      <ul>
{render_stats(c)}
      </ul>
    </div>
  </section>

  <section class="section" id="profile">
    <div class="wrap section-grid">
      {section_label(profile)}
      <div>
        <p class="statement">{fmt(profile["statement"])}</p>
        <p class="statement-sub">{fmt(profile["sub"])}</p>
      </div>
    </div>
  </section>

  <section class="section" id="expertise">
    <div class="wrap section-grid">
      {section_label(c["expertise"])}
      <ul class="expertise">
{render_expertise(c)}
      </ul>
    </div>
  </section>

  <section class="section" id="career">
    <div class="wrap section-grid">
      {section_label(c["career"])}
      <div>

{render_career(c)}

        <p class="service-note">{fmt(c["career"]["service_note"])}</p>
      </div>
    </div>
  </section>

  <section class="section" id="education">
    <div class="wrap section-grid">
      {section_label(c["education"])}
      <ul class="edu">
{render_education(c)}
      </ul>
    </div>
  </section>

  <section class="section" id="research">
    <div class="wrap section-grid">
      {section_label(c["research"])}
      <div>
        {render_research(c, s)}
      </div>
    </div>
  </section>

  <section class="contact" id="contact">
    <div class="wrap">
      <div class="contact-panel">
        <div>
          <span class="eyebrow">{fmt(ct["eyebrow"])}</span>
          <h2>{fmt(ct["title"])}</h2>
          <p class="contact-body">{fmt(ct["body"])}</p>
          <div class="topics">
            <div class="topics-label">{fmt(ct["topics_label"])}</div>
            <ul>
{topics}
            </ul>
          </div>
        </div>
        <div class="contact-card">
          <dl>
            <div>
              <dt>{fmt(ct["email_label"])}</dt>
              <dd>{s["email"]} <button class="copy-btn" type="button" data-copy="{s["email"]}" data-done="{attr(ui["copied"])}" data-fail="{attr(ui["copy_failed"])}">{fmt(ui["copy"])}</button></dd>
            </div>
            <div>
              <dt>{fmt(ct["phone_label"])}</dt>
              <dd class="num">{s["phone"]}</dd>
            </div>
            <div>
              <dt>{fmt(ct["location_label"])}</dt>
              <dd>{fmt(ct["location"])}</dd>
            </div>
          </dl>
          <div class="contact-actions">
            <a class="btn btn-primary" href="mailto:{s["email"]}">{fmt(ct["cta_email"])}</a>
            <a class="btn btn-secondary" href="tel:{s["phone_tel"]}">{fmt(ct["cta_phone"])}</a>
          </div>
        </div>
      </div>
    </div>
  </section>

</main>

<footer>
  <div class="wrap">
    <span>{fmt(ui["copyright"])}</span>
    <span>{fmt(ui["footer_tagline"])}</span>
  </div>
</footer>

<script src="../assets/site.js" defer></script>

</body>
</html>
"""


ROUTER_SCRIPT = """<script>
  (function () {
    var supported = __SUPPORTED__;
    var pick = null;
    try { pick = localStorage.getItem(__KEY__); } catch (e) {}
    if (supported.indexOf(pick) < 0) {
      pick = null;
      var prefs = navigator.languages || [navigator.language || ''];
      for (var i = 0; i < prefs.length && !pick; i++) {
        var code = String(prefs[i]).slice(0, 2).toLowerCase();
        if (supported.indexOf(code) >= 0) pick = code;
      }
    }
    location.replace((pick || __DEFAULT__) + '/' + location.hash);
  })();
</script>"""


def router(s, langs):
    script = (
        ROUTER_SCRIPT.replace("__SUPPORTED__", json.dumps(LANG_ORDER))
        .replace("__KEY__", json.dumps(STORAGE_KEY))
        .replace("__DEFAULT__", json.dumps(DEFAULT_LANG))
    )
    head = head_common(
        "Sung Hun Kim, Ph.D. · 김성헌",
        "Sung Hun Kim, Ph.D. — Lead Scientist, SABIC Asia-Pacific. 한국어 · English · 简体中文",
        s["site_url"], "Sung Hun Kim, Ph.D. · 김성헌",
        "Lead Scientist, SABIC Asia-Pacific · Polymer materials technology and global business development",
        "en_US", [l["og_locale"] for l in langs if l["og_locale"] != "en_US"], langs, s, "",
    )
    links = "\n".join(
        f'      <li><a href="{l["code"]}/" lang="{l["hreflang"]}" hreflang="{l["hreflang"]}">{fmt(l["native"])}</a></li>'
        for l in langs
    )
    return f"""<!doctype html>
{NOTICE}
<html lang="en">
<head>
{script}
{head}
</head>
<body>
  <main class="lang-gate">
    <span class="eyebrow">Polymer Materials · Technology &amp; Business Development</span>
    <h1>Sung Hun Kim, Ph.D. <span lang="ko">김성헌</span></h1>
    <ul>
{links}
    </ul>
  </main>
</body>
</html>
"""


def main():
    shared, langs = load()
    for c in langs:
        out = ROOT / c["code"] / "index.html"
        out.parent.mkdir(exist_ok=True)
        out.write_text(page(c, shared, langs), encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(ROOT)}")
    (ROOT / "index.html").write_text(router(shared, langs), encoding="utf-8", newline="\n")
    print("wrote index.html")


if __name__ == "__main__":
    main()
